twig:
  form_themes:
    - "@FMElfinder/Form/elfinder_widget.html.twig"
  file_name_pattern: "*.twig"
  cache: "%kernel.cache_dir%/twig"

when@dev:
  twig:
    cache: false
    strict_variables: true

when@test:
  twig:
    strict_variables: true
